server:
  port: 9090
  
spring:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate: 
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    generate-unique-name: true
  h2:
    console:
      enabled: true
      
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
